version: "2.15.1"

services:
  postgres:
    image: postgres:14.6
    container_name: postgres_compose
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_NAME: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

volumes:
  postgres:
    driver: local

